version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: medical-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ProjetPFA2026
      MYSQL_DATABASE: medical_db
    volumes:
      - mysql_data:/var/lib/mysql

  backend-app:
    build:
      context: ./backend
    container_name: medical-backend-app
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: ProjetPFA2026
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mysql-db

  frontend-app:
    container_name: medical-frontend-app
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend-app

volumes:
  mysql_data: