services:
  mysql-db:
    image: mysql:8.0
    container_name: medical-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ProjetPFA2026
      MYSQL_DATABASE: medical_db
    volumes:
      - mysql_data:/var/lib/mysql

  backend-app:
    build:
      context: ./backend
    container_name: medical-backend-app
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: ProjetPFA2026
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mysql-db

  frontend-app:
    container_name: medical-frontend-app
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend-app

  prometheus:
    image: prom/prometheus:latest
    container_name: medical-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend-app

  grafana:
    image: grafana/grafana:latest
    container_name: medical-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: medical-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: medical-logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: medical-kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch


volumes:
  mysql_data:
  es_data: